name: Build

on: [ push, workflow_dispatch ]

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: configuration-cache-report
          path: build/reports/configuration-cache/**/configuration-cache-report.html
